version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - StevePoling-Resume.pdf
    - styles/*
    - images/*
    - dist/bundle.js
